/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/lib/i18n`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/doctor/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/doctor`; params?: Router.UnknownInputParams; } | { pathname: `/lib/gemini`; params?: Router.UnknownInputParams; } | { pathname: `/lib/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/patient/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/patient`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/i18n`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/doctor/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/doctor`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/gemini`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/patient/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/patient`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/lib/i18n${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/doctor/dashboard${`?${string}` | `#${string}` | ''}` | `/doctor${`?${string}` | `#${string}` | ''}` | `/lib/gemini${`?${string}` | `#${string}` | ''}` | `/lib/supabase${`?${string}` | `#${string}` | ''}` | `/patient/dashboard${`?${string}` | `#${string}` | ''}` | `/patient${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/lib/i18n`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/doctor/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/doctor`; params?: Router.UnknownInputParams; } | { pathname: `/lib/gemini`; params?: Router.UnknownInputParams; } | { pathname: `/lib/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/patient/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/patient`; params?: Router.UnknownInputParams; };
    }
  }
}
